"""Story Pack Pydantic models.

Every page on disk is a Markdown file with YAML frontmatter. The frontmatter
holds machine-readable metadata (slug, name, type-specific fields). The body
is free-form prose the LLM reads for flavor.

The canonical Pack is a container of typed entity pages plus top-level
meta-pages. Loader/writer round-trip is lossy only for fields we don't model
(those live in `extra`), never for schema fields.
"""

from __future__ import annotations

from typing import Literal

from pydantic import BaseModel, ConfigDict, Field, model_validator

EntityCategory = Literal["character", "faction", "location", "system", "arc", "event"]
PackKind = Literal["genre", "user"]


class PageBase(BaseModel):
    """Envelope common to every page type: slug, body, and pass-through extras."""

    model_config = ConfigDict(extra="allow")

    slug: str = Field(..., description="Unique snake_case id within its category.")
    name: str = Field(..., description="Display name.")
    body: str = Field("", description="Markdown prose body (after frontmatter).")


class CharacterPage(PageBase):
    category: Literal["character"] = "character"
    aliases: list[str] = Field(default_factory=list)
    role: str | None = Field(default=None, description="Free-form role label: protagonist, master, rival, ...")
    sect: str | None = Field(default=None, description="Slug of affiliated faction, if any.")
    cultivation_stage: str | None = None
    status: Literal["alive", "dead", "injured", "missing", "unknown"] = "alive"
    location: str | None = Field(default=None, description="Slug of a location page, if resident.")


class FactionPage(PageBase):
    category: Literal["faction"] = "faction"
    alignment: str | None = None
    seat: str | None = Field(default=None, description="Slug of a location page.")
    leaders: list[str] = Field(default_factory=list)


class LocationPage(PageBase):
    category: Literal["location"] = "location"
    region: str | None = None
    controlled_by: str | None = Field(default=None, description="Faction slug.")
    danger: Literal["safe", "guarded", "hostile", "deadly"] = "safe"


class SystemPage(PageBase):
    category: Literal["system"] = "system"
    kind: str | None = Field(default=None, description="e.g. cultivation, items, social_rules.")


class ArcPage(PageBase):
    category: Literal["arc"] = "arc"
    summary: str = ""
    status: Literal["opening", "active", "suspended", "closed"] = "opening"
    driving_entities: list[str] = Field(default_factory=list)


class EventPage(PageBase):
    category: Literal["event"] = "event"
    kind: Literal["key", "triggerable", "dangerous_divergence"] = "key"
    preconditions: list[str] = Field(default_factory=list)


class MetaPage(BaseModel):
    """A top-level reference page (index.md, overview.md, etc.) with optional frontmatter."""

    model_config = ConfigDict(extra="allow")

    name: str
    body: str = ""


class Pack(BaseModel):
    """A fully loaded Story Pack (either a genre template or a user pack)."""

    model_config = ConfigDict(extra="forbid")

    name: str = Field(..., description="Pack directory name.")
    kind: PackKind = Field(..., description="'genre' for reusable templates; 'user' for novel-generated packs.")
    inherits_genre: str | None = Field(
        default=None,
        description="Required for user packs: the genre pack name to stack against. Must be None for genre packs.",
    )

    # Top-level meta pages
    index: MetaPage | None = None
    overview: MetaPage | None = None
    style_guide: MetaPage | None = None
    canon_guardrails: MetaPage | None = None
    timeline: MetaPage | None = None
    relationships: MetaPage | None = None
    ambiguities: MetaPage | None = None

    # Entity pages (user packs only; genre packs forbid these)
    characters: list[CharacterPage] = Field(default_factory=list)
    factions: list[FactionPage] = Field(default_factory=list)
    locations: list[LocationPage] = Field(default_factory=list)
    systems: list[SystemPage] = Field(default_factory=list)
    arcs: list[ArcPage] = Field(default_factory=list)
    events: list[EventPage] = Field(default_factory=list)

    @model_validator(mode="after")
    def _enforce_kind_rules(self) -> "Pack":
        if self.kind == "genre":
            if self.inherits_genre is not None:
                raise ValueError("genre packs must not declare inherits_genre")
            # Systems are genre-level mechanics (cultivation, social_rules) and are permitted.
            # Characters, factions, locations, arcs, events are novel-specific and forbidden.
            if any((self.characters, self.factions, self.locations, self.arcs, self.events)):
                raise ValueError(
                    "genre packs must not contain novel-specific entity pages "
                    "(characters/factions/locations/arcs/events). "
                    "Those belong in a user pack generated by `sirengm ingest`."
                )
        else:  # user
            if not self.inherits_genre:
                raise ValueError("user packs must declare inherits_genre in their index.md frontmatter")
        return self

    def find_entity(self, slug: str) -> PageBase | None:
        """Look up any entity by slug across all categories."""
        for bucket in (self.characters, self.factions, self.locations, self.systems, self.arcs, self.events):
            for page in bucket:
                if page.slug == slug:
                    return page
        return None

    def all_entity_slugs(self) -> set[str]:
        slugs: set[str] = set()
        for bucket in (self.characters, self.factions, self.locations, self.systems, self.arcs, self.events):
            slugs.update(p.slug for p in bucket)
        return slugs
